name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  upload-release-assets:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        artifact:
          - devtools-x86
          - devtools-x64
          - devtools-x86-debug
          - devtools-x64-debug
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: ./artifacts

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./artifacts/${{ matrix.artifact }}.zip
        asset_name: ${{ matrix.artifact }}.zip
        asset_content_type: application/zip
